# -*- coding: utf-8 -*-
"""Traducciones del sitio. Clave = texto en español tal como está en build.py.
Si una clave falta, se muestra el español."""

EN = {
    # navegación y puertas
    "Técnica de proyectos": "Project technician",
    "Diseño de marca": "Brand design",
    "Hostelería y ventas": "Hospitality & retail",
    "Cálculo, presupuesto y dibujo.": "Quantities, budgets and drawings.",
    "Pienso la marca y la dibujo.": "I think the brand, then I draw it.",
    "Trabajo donde haga falta.": "I work wherever I'm needed.",
    "Ingeniera civil como asistente técnica o colaboradora en estudios y empresas: cómputos, presupuestos, dibujo y documentación de proyecto. Me integro rápido a un equipo y trabajo con orden.":
        "Civil engineer working as a technical assistant or collaborator for studios and companies: quantity take-offs, budgets, drafting and project documentation. I settle into a team quickly and work in an orderly way.",
    "Diseñadora de marca desde 2018. Identidad visual, manuales, aplicaciones y, cuando el proyecto lo pide, escenas del espacio en arte digital y motion.":
        "Brand designer since 2018. Visual identity, brand guidelines, applications and, when the project calls for it, scenes of the space in digital art and motion.",
    "Housekeeper en hoteles, catering assistant en eventos, dishwasher en restaurantes y sales assistant en tienda. Temporadas de verano e invierno en Italia, Australia y España.<br>Espero que mi experiencia sea útil para tu equipo.":
        "Housekeeper in hotels, catering assistant at events, dishwasher in restaurants and sales assistant in retail. Summer and winter seasons in Italy, Australia and Spain.<br>I hope my experience can be useful to your team.",
    "Disponibilidad inmediata · presencial en Valencia o en remoto desde cualquier lugar": "Available immediately · on site in Valencia or remotely from anywhere",
    "Disponibilidad inmediata · España (incluidas las islas), Italia, Suiza, Noruega, Islandia y Países Bajos": "Available immediately · Spain (islands included), Italy, Switzerland, Norway, Iceland and the Netherlands",
    "Contacto desde la web": "Contact from the website",
    # pilares
    "Cómputos y presupuestos": "Quantities and budgets",
    "Mediciones, cuantificación y presupuesto de proyecto, con documentación clara y ordenada.": "Measurements, quantity take-offs and project budgets, with clear and orderly documentation.",
    "Dibujo técnico": "Technical drawing",
    "Plantas, cortes, alzados y detalles en AutoCAD. Modelado 3D en SketchUp y Revit.": "Plans, sections, elevations and details in AutoCAD. 3D modelling in SketchUp and Revit.",
    "Documentación de proyecto": "Project documentation",
    "Organización de la información técnica, relevamientos, memorias y material gráfico para presentar.": "Organising technical information, site surveys, reports and graphic material for presentations.",
    "La marca": "The brand",
    "Pienso el concepto y dibujo el logotipo, el sistema de color y la tipografía.": "I develop the concept and draw the logo, the colour system and the typography.",
    "Las aplicaciones": "The applications",
    "Manual de marca, envases y etiquetas, piezas para redes, cartelería y material corporativo.": "Brand guidelines, packaging and labels, social media pieces, signage and corporate material.",
    "El espacio": "The space",
    "Visualizaciones de la marca en su lugar: arte digital y motion sobre escenas arquitectónicas.": "Visualisations of the brand in its place: digital art and motion over architectural scenes.",
    "Housekeeping": "Housekeeping",
    "Camarera de pisos en hotel boutique, limpieza residencial y comercial, mantenimiento de áreas comunes.": "Room attendant in a boutique hotel, residential and commercial cleaning, upkeep of common areas.",
    "Cocina y eventos": "Kitchen and events",
    "Lavaplatos y auxiliar de cocina en ritmo alto. Preparación y servicio en eventos de catering.": "Dishwasher and kitchen hand at a fast pace. Set-up and service at catering events.",
    "Sales assistant / retail": "Sales assistant / retail",
    "Asesoramiento, reposición, gestión de stock con PDA y visual merchandising en Zara Home.": "Customer advice, restocking, stock management with a handheld scanner and visual merchandising at Zara Home.",
    # muestras
    "Plantas, corte y axonometría · de la línea al collage": "Plans, section and axonometric · from line to collage",
    "Vestidor · alzado interior": "Walk-in wardrobe · interior elevation",
    "Interior · línea": "Interior · line drawing",
    "Textura de la selva · pieza del collage": "Jungle texture · collage piece",
    "Proceso · tableta": "Process · tablet",
    "Escena del espacio · escritorio": "Scene of the space · desk",
    "Escena animada · escritorio": "Animated scene · desk",
    "Escena del espacio · cocina": "Scene of the space · kitchen",
    "Escena animada · cocina": "Animated scene · kitchen",
    "Escena del espacio · baño": "Scene of the space · bathroom",
    "Escena animada · baño": "Animated scene · bathroom",
    "Cuadro animado · ola": "Animated picture · wave",
    "Paleta de materiales": "Material palette",
    "Collage de objetos y materiales": "Collage of objects and materials",
    "Muestras de trabajo.": "Work samples.",
    "Proyectos.": "Projects.",
    "Marcas.": "Brands.",
    "Logotipo": "Logo",
    "alterna sola; tocar para pasar a la siguiente": "changes on its own; tap to go to the next one",
    "vista": "view",
    # trayectoria
    "Valencia, España": "Valencia, Spain",
    "Passo del Tonale, Italia": "Passo del Tonale, Italy",
    "Sídney, Australia": "Sydney, Australia",
    "Sicilia, Italia": "Sicily, Italy",
    "Italia · remoto": "Italy · remote",
    "Colombia · remoto": "Colombia · remote",
    "Remoto": "Remote",
    "Dependienta y asesora de ventas": "Sales assistant",
    "Atención al cliente, reposición, gestión de stock con PDA, visual merchandising.": "Customer service, restocking, stock management with a handheld scanner, visual merchandising.",
    "Estancia en Argentina": "Stay in Argentina",
    "Familia y viaje": "Family and travel",
    "Entre la temporada de Australia y la de Italia.": "Between the Australian season and the Italian one.",
    "Polivalente de hotel · housekeeping": "Hotel all-rounder · housekeeping",
    "Temporada de invierno: habitaciones y zonas comunes, spa y gimnasio, sala de esquís y lavandería.": "Winter season: rooms and common areas, spa and gym, ski room and laundry.",
    "Voluntaria": "Volunteer",
    "Proyecto MINCA y casa de familia": "MINCA project and family home",
    "Conservación de flora nativa, mantenimiento ambiental y apoyo doméstico.": "Native flora conservation, environmental maintenance and household support.",
    "Polivalente": "All-rounder",
    "Limpieza, mantenimiento general y apoyo en visitas guiadas de fruta tropical.": "Cleaning, general maintenance and help with tropical fruit tours.",
    "Polivalente de hotel": "Hotel all-rounder",
    "Limpieza, ayuda en cocina y tareas generales del hotel. Voluntariado en casa de familia en paralelo.": "Cleaning, kitchen help and general hotel duties. Volunteering in a family home at the same time.",
    "Auxiliar de catering": "Catering assistant",
    "Montaje de eventos, servicio y atención al público.": "Event set-up, service and customer care.",
    "Auxiliar de limpieza": "Cleaner",
    "Limpieza residencial y comercial, trabajo autónomo con estándares de calidad.": "Residential and commercial cleaning, working independently to quality standards.",
    "Lavaplatos y apoyo de sala": "Dishwasher and front-of-house support",
    "Apoyo general de restaurante.": "General restaurant support.",
    "Camarera de pisos": "Room attendant",
    "Limpieza y preparación de habitaciones y áreas comunes en hotel boutique.": "Cleaning and preparing rooms and common areas in a boutique hotel.",
    "Lavaplatos y auxiliar de cocina": "Dishwasher and kitchen hand",
    "Cocina en ritmo alto, coordinación con el equipo.": "Fast-paced kitchen, coordinating with the team.",
    "Técnica de proyectos arquitectónicos": "Architectural project technician",
    "Cómputos, presupuestos y documentación de proyecto. Relevamientos, modelado 3D y material gráfico. Apoyo a la dirección del estudio.": "Quantity take-offs, budgets and project documentation. Site surveys, 3D modelling and graphic material. Support to the studio's management.",
    "Diseñadora de proyectos arquitectónicos": "Architectural project designer",
    "Propuestas espaciales y tipológicas, apoyo técnico para la viabilidad, documentación y material gráfico.": "Spatial and typological proposals, technical support for feasibility, documentation and graphic material.",
    "Diseñadora gráfica": "Graphic designer",
    "Contenido para campañas digitales y redes, adaptación de identidades para distintas marcas.": "Content for digital campaigns and social media, adapting identities for different brands.",
    "Diseñadora de marca independiente": "Freelance brand designer",
    "Clientes propios": "Own clients",
    "Identidades visuales, logotipos, manuales de marca, editorial, envases y etiquetas. Gestión completa del proyecto con el cliente.": "Visual identities, logos, brand guidelines, editorial design, packaging and labels. Full project management with the client.",
    "Ingeniería Civil": "Civil Engineering",
    "Título de Ingeniera Civil.": "Degree in Civil Engineering.",
    "Bachiller en Economía y Gestión de las Organizaciones": "High school diploma in Economics and Business Management",
    "hoy": "today",
    "Técnica": "Technical", "Marca": "Brand", "Hostelería": "Hospitality", "Formación": "Education", "Viaje": "Travel",
    # herramientas, idiomas, ficha
    "Diseño": "Design", "Oficina": "Office", "Inteligencia artificial": "Artificial intelligence",
    "Español": "Spanish", "Italiano": "Italian", "Inglés": "English", "Nativo": "Native",
    "Ciudadanía": "Citizenship",
    "Italiana y argentina. Permiso de trabajo en toda la Unión Europea.": "Italian and Argentine. Entitled to work anywhere in the European Union.",
    "Carnet de conducir": "Driving licence", "No.": "No", "Movilidad": "Mobility",
    "Disponibilidad inmediata. Presencial en Valencia o en remoto desde cualquier lugar.": "Available immediately. On site in Valencia or remotely from anywhere.",
    "Disponibilidad inmediata. Puedo mudarme dentro de España (incluidas las islas) y a Italia, Suiza, Noruega, Islandia y Países Bajos.": "Available immediately. I can relocate within Spain (islands included) and to Italy, Switzerland, Norway, Iceland and the Netherlands.",
    "Presencial en Valencia, en remoto desde cualquier lugar, o con traslado dentro de España y a Italia, Suiza, Noruega, Islandia y Países Bajos.": "On site in Valencia, remotely from anywhere, or relocating within Spain and to Italy, Switzerland, Norway, Iceland and the Netherlands.",
    # presentación
    "Gracias por llegar hasta aquí.": "Thank you for reading this far.",
    "Durante mucho tiempo pensé que tenía que elegir entre el cálculo y el dibujo. Estudié ingeniería, y mientras tanto aprendí diseño por mi cuenta, proyecto a proyecto, desde 2018. Con los años entendí que no eran dos caminos: la ingeniería me enseñó responsabilidad y constancia, a medir antes de opinar y a documentar bien; el diseño, a mirar cómo se siente un lugar y a escuchar lo que alguien necesita antes de dibujarlo. Hoy trabajo con las dos cosas a la vez.":
        "For a long time I thought I had to choose between calculation and drawing. I studied engineering and, in the meantime, taught myself design, project by project, since 2018. Over the years I understood they were not two separate paths: engineering taught me responsibility and perseverance, to measure before giving an opinion and to document properly; design taught me to notice how a place feels and to listen to what someone needs before drawing it. Today I work with both at once.",
    "Los últimos años fueron de viaje y de trabajo. Trabajé de manera independiente y en estudios con equipos grandes dentro de mi profesión; también fui ayudante de cocina, hice camas en hoteles, lavé platos en restaurantes y serví eventos grandes en Italia y pequeños en Australia. Eso me enseñó lo que vale llegar a tiempo, hacer bien lo que toca y cuidar a la persona que tienes delante. También a trabajar codo a codo con gente de todas partes, a no perder la calma cuando el ritmo aprieta y, de paso, a cocinar mucho mejor.":
        "The last few years have been about travelling and working. I worked independently and in studios with large teams within my profession; I was also a kitchen hand, made beds in hotels, washed dishes in restaurants and served large events in Italy and small ones in Australia. That taught me the value of being on time, doing well whatever needs doing and looking after the person in front of you. It also taught me to work side by side with people from everywhere, to keep calm when the pace picks up and, along the way, to cook much better.",
    "Me gusta preguntar mucho antes de empezar y explicar el porqué de cada decisión.": "I like to ask a lot of questions before starting and to explain the reason behind every decision.",
    "Viajo desde que terminé la carrera y la curiosidad no se me ha pasado: ya son casi veinte países, algunos apenas de paso. Por eso llevo a todas partes una cámara de segunda mano: para retratar lo que no quiero olvidar.":
        "I have been travelling since I finished my degree and my curiosity hasn't worn off: almost twenty countries so far, some only passing through. That's why I carry a second-hand camera everywhere: to capture what I don't want to forget.",
    "Si estás leyendo esto, seguramente buscas a alguien para tu estudio, tu restaurante, tu local o tu hotel. Me encantaría contarte más en persona. Escríbeme.":
        "If you're reading this, you're probably looking for someone for your studio, your restaurant, your shop or your hotel. I'd love to tell you more in person. Write to me.",
    # secciones y varios
    "Quién soy.": "Who I am.", "Qué hago.": "What I do.", "Toda la trayectoria.": "The whole journey.",
    "Desde 2007 hasta la actualidad.": "From 2007 to today.", "Lo práctico.": "The practical side.",
    "Herramientas e idiomas.": "Tools and languages.", "Idiomas": "Languages", "Fotografía.": "Photography.",
    "Mi afición. Me ayuda a desconectar y a mirar mejor.": "My hobby. It helps me switch off and look more closely.",
    "Hablemos.": "Let's talk.", "Un correo o un mensaje. Respondo en el día.": "An email or a message. I reply the same day.",
    "Descargar el CV en PDF": "Download my CV (PDF)",
    "Escríbeme": "Write to me", "Volver arriba": "Back to top", "Entrar": "Enter", "Menú": "Menu",
    "Ir al contenido": "Skip to content", "Cambiar entre modo claro y oscuro": "Switch between light and dark mode",
    "Modo claro / oscuro": "Light / dark mode", "Áreas": "Areas", "fotos": "photos", "Idioma": "Language",
    "Valencia, España · 2026": "Valencia, Spain · 2026", "Passo del Tonale, Italia · 2026": "Passo del Tonale, Italy · 2026",
    "Ingeniera civil · Técnica de proyectos · Diseñadora gráfica": "Civil engineer · Project technician · Graphic designer",
    "Natalia Giordano.": "Natalia Giordano.",
    "Ingeniera civil y diseñadora gráfica argentina, viviendo actualmente en Valencia, España. Elige el área que te interesa: verás primero lo que buscas y, debajo, toda la trayectoria.":
        "Argentine civil engineer and graphic designer, currently living in Valencia, Spain. Choose the area you're interested in: you'll see what you're looking for first and, below it, the whole journey.",
    "Ingeniera civil, técnica de proyectos y diseñadora de marca en Valencia. Cómputos y presupuestos, diseño de marca, hostelería y ventas.":
        "Civil engineer, project technician and brand designer in Valencia. Quantities and budgets, brand design, hospitality and retail.",
    "Ingeniera civil · Diseñadora de marca": "Civil engineer · Brand designer",
    "Hola Natalia, vi tu portafolio y me gustaría hablar contigo.": "Hi Natalia, I saw your portfolio and I'd like to get in touch.",
    "Correo copiado": "Email copied",
    "Copiar": "Copy", "Abrir en Gmail": "Open in Gmail", "Abrir en Outlook": "Open in Outlook",
    "Programa de correo": "Mail app", "Cerrar": "Close", "Escribir a": "Write to",
}

IT = {
    "Técnica de proyectos": "Tecnica progettista",
    "Diseño de marca": "Design del marchio",
    "Hostelería y ventas": "Ospitalità e vendita",
    "Cálculo, presupuesto y dibujo.": "Computi, preventivi e disegno.",
    "Pienso la marca y la dibujo.": "Penso il marchio e lo disegno.",
    "Trabajo donde haga falta.": "Lavoro dove serve.",
    "Ingeniera civil como asistente técnica o colaboradora en estudios y empresas: cómputos, presupuestos, dibujo y documentación de proyecto. Me integro rápido a un equipo y trabajo con orden.":
        "Ingegnera civile come assistente tecnica o collaboratrice per studi e aziende: computi metrici, preventivi, disegno e documentazione di progetto. Mi inserisco in fretta in un team e lavoro con ordine.",
    "Diseñadora de marca desde 2018. Identidad visual, manuales, aplicaciones y, cuando el proyecto lo pide, escenas del espacio en arte digital y motion.":
        "Brand designer dal 2018. Identità visiva, manuali, applicazioni e, quando il progetto lo richiede, scene dello spazio in arte digitale e motion.",
    "Housekeeper en hoteles, catering assistant en eventos, dishwasher en restaurantes y sales assistant en tienda. Temporadas de verano e invierno en Italia, Australia y España.<br>Espero que mi experiencia sea útil para tu equipo.":
        "Housekeeper in hotel, catering assistant per eventi, lavapiatti nei ristoranti e sales assistant in negozio. Stagioni estive e invernali in Italia, Australia e Spagna.<br>Spero che la mia esperienza possa essere utile al tuo team.",
    "Disponibilidad inmediata · presencial en Valencia o en remoto desde cualquier lugar": "Disponibilità immediata · in presenza a Valencia o da remoto da qualsiasi luogo",
    "Disponibilidad inmediata · España (incluidas las islas), Italia, Suiza, Noruega, Islandia y Países Bajos": "Disponibilità immediata · Spagna (isole comprese), Italia, Svizzera, Norvegia, Islanda e Paesi Bassi",
    "Contacto desde la web": "Contatto dal sito",
    "Cómputos y presupuestos": "Computi e preventivi",
    "Mediciones, cuantificación y presupuesto de proyecto, con documentación clara y ordenada.": "Misurazioni, computi metrici e preventivi di progetto, con documentazione chiara e ordinata.",
    "Dibujo técnico": "Disegno tecnico",
    "Plantas, cortes, alzados y detalles en AutoCAD. Modelado 3D en SketchUp y Revit.": "Piante, sezioni, prospetti e dettagli in AutoCAD. Modellazione 3D in SketchUp e Revit.",
    "Documentación de proyecto": "Documentazione di progetto",
    "Organización de la información técnica, relevamientos, memorias y material gráfico para presentar.": "Organizzazione delle informazioni tecniche, rilievi, relazioni e materiale grafico per le presentazioni.",
    "La marca": "Il marchio",
    "Pienso el concepto y dibujo el logotipo, el sistema de color y la tipografía.": "Penso il concetto e disegno il logotipo, il sistema colore e la tipografia.",
    "Las aplicaciones": "Le applicazioni",
    "Manual de marca, envases y etiquetas, piezas para redes, cartelería y material corporativo.": "Manuale del marchio, packaging ed etichette, contenuti per i social, cartellonistica e materiale aziendale.",
    "El espacio": "Lo spazio",
    "Visualizaciones de la marca en su lugar: arte digital y motion sobre escenas arquitectónicas.": "Visualizzazioni del marchio nel suo luogo: arte digitale e motion su scene architettoniche.",
    "Housekeeping": "Housekeeping",
    "Camarera de pisos en hotel boutique, limpieza residencial y comercial, mantenimiento de áreas comunes.": "Cameriera ai piani in un hotel boutique, pulizie residenziali e commerciali, manutenzione delle aree comuni.",
    "Cocina y eventos": "Cucina ed eventi",
    "Lavaplatos y auxiliar de cocina en ritmo alto. Preparación y servicio en eventos de catering.": "Lavapiatti e aiuto cucina a ritmo alto. Preparazione e servizio in eventi di catering.",
    "Sales assistant / retail": "Sales assistant / retail",
    "Asesoramiento, reposición, gestión de stock con PDA y visual merchandising en Zara Home.": "Consulenza al cliente, rifornimento, gestione dello stock con palmare e visual merchandising da Zara Home.",
    "Plantas, corte y axonometría · de la línea al collage": "Piante, sezione e assonometria · dalla linea al collage",
    "Vestidor · alzado interior": "Cabina armadio · prospetto interno",
    "Interior · línea": "Interno · linea",
    "Textura de la selva · pieza del collage": "Texture della giungla · pezzo del collage",
    "Proceso · tableta": "Processo · tavoletta",
    "Escena del espacio · escritorio": "Scena dello spazio · scrivania",
    "Escena animada · escritorio": "Scena animata · scrivania",
    "Escena del espacio · cocina": "Scena dello spazio · cucina",
    "Escena animada · cocina": "Scena animata · cucina",
    "Escena del espacio · baño": "Scena dello spazio · bagno",
    "Escena animada · baño": "Scena animata · bagno",
    "Cuadro animado · ola": "Quadro animato · onda",
    "Paleta de materiales": "Palette dei materiali",
    "Collage de objetos y materiales": "Collage di oggetti e materiali",
    "Muestras de trabajo.": "Esempi di lavoro.",
    "Proyectos.": "Progetti.",
    "Marcas.": "Marchi.",
    "Logotipo": "Logotipo",
    "alterna sola; tocar para pasar a la siguiente": "cambia da sola; tocca per passare alla successiva",
    "vista": "vista",
    "Valencia, España": "Valencia, Spagna",
    "Sídney, Australia": "Sydney, Australia",
    "Italia · remoto": "Italia · da remoto",
    "Colombia · remoto": "Colombia · da remoto",
    "Remoto": "Da remoto",
    "Dependienta y asesora de ventas": "Commessa e consulente di vendita",
    "Atención al cliente, reposición, gestión de stock con PDA, visual merchandising.": "Assistenza al cliente, rifornimento, gestione dello stock con palmare, visual merchandising.",
    "Estancia en Argentina": "Periodo in Argentina",
    "Familia y viaje": "Famiglia e viaggio",
    "Entre la temporada de Australia y la de Italia.": "Tra la stagione in Australia e quella in Italia.",
    "Polivalente de hotel · housekeeping": "Addetta polivalente d'albergo · housekeeping",
    "Temporada de invierno: habitaciones y zonas comunes, spa y gimnasio, sala de esquís y lavandería.": "Stagione invernale: camere e aree comuni, spa e palestra, sala sci e lavanderia.",
    "Voluntaria": "Volontaria",
    "Proyecto MINCA y casa de familia": "Progetto MINCA e casa di famiglia",
    "Conservación de flora nativa, mantenimiento ambiental y apoyo doméstico.": "Conservazione della flora nativa, manutenzione ambientale e supporto domestico.",
    "Polivalente": "Addetta polivalente",
    "Limpieza, mantenimiento general y apoyo en visitas guiadas de fruta tropical.": "Pulizie, manutenzione generale e supporto nelle visite guidate di frutta tropicale.",
    "Polivalente de hotel": "Addetta polivalente d'albergo",
    "Limpieza, ayuda en cocina y tareas generales del hotel. Voluntariado en casa de familia en paralelo.": "Pulizie, aiuto in cucina e mansioni generali dell'hotel. In parallelo, volontariato in una casa di famiglia.",
    "Auxiliar de catering": "Catering assistant",
    "Montaje de eventos, servicio y atención al público.": "Allestimento eventi, servizio e assistenza al pubblico.",
    "Auxiliar de limpieza": "Addetta alle pulizie",
    "Limpieza residencial y comercial, trabajo autónomo con estándares de calidad.": "Pulizie residenziali e commerciali, lavoro autonomo con standard di qualità.",
    "Lavaplatos y apoyo de sala": "Lavapiatti e supporto in sala",
    "Apoyo general de restaurante.": "Supporto generale al ristorante.",
    "Camarera de pisos": "Cameriera ai piani",
    "Limpieza y preparación de habitaciones y áreas comunes en hotel boutique.": "Pulizia e preparazione di camere e aree comuni in un hotel boutique.",
    "Lavaplatos y auxiliar de cocina": "Lavapiatti e aiuto cucina",
    "Cocina en ritmo alto, coordinación con el equipo.": "Cucina a ritmo alto, coordinamento con il team.",
    "Técnica de proyectos arquitectónicos": "Tecnica progettista architettonica",
    "Cómputos, presupuestos y documentación de proyecto. Relevamientos, modelado 3D y material gráfico. Apoyo a la dirección del estudio.": "Computi metrici, preventivi e documentazione di progetto. Rilievi, modellazione 3D e materiale grafico. Supporto alla direzione dello studio.",
    "Diseñadora de proyectos arquitectónicos": "Progettista architettonica",
    "Propuestas espaciales y tipológicas, apoyo técnico para la viabilidad, documentación y material gráfico.": "Proposte spaziali e tipologiche, supporto tecnico alla fattibilità, documentazione e materiale grafico.",
    "Diseñadora gráfica": "Graphic designer",
    "Contenido para campañas digitales y redes, adaptación de identidades para distintas marcas.": "Contenuti per campagne digitali e social, adattamento di identità per diversi marchi.",
    "Diseñadora de marca independiente": "Brand designer freelance",
    "Clientes propios": "Clienti propri",
    "Identidades visuales, logotipos, manuales de marca, editorial, envases y etiquetas. Gestión completa del proyecto con el cliente.": "Identità visive, logotipi, manuali del marchio, grafica editoriale, packaging ed etichette. Gestione completa del progetto con il cliente.",
    "Ingeniería Civil": "Ingegneria Civile",
    "Título de Ingeniera Civil.": "Laurea in Ingegneria Civile.",
    "Bachiller en Economía y Gestión de las Organizaciones": "Diploma in Economia e Gestione delle Organizzazioni",
    "hoy": "oggi",
    "Técnica": "Tecnica", "Marca": "Marchio", "Hostelería": "Ospitalità", "Formación": "Formazione", "Viaje": "Viaggio",
    "Diseño": "Design", "Oficina": "Ufficio", "Inteligencia artificial": "Intelligenza artificiale",
    "Español": "Spagnolo", "Italiano": "Italiano", "Inglés": "Inglese", "Nativo": "Madrelingua",
    "Ciudadanía": "Cittadinanza",
    "Italiana y argentina. Permiso de trabajo en toda la Unión Europea.": "Italiana e argentina. Permesso di lavoro in tutta l'Unione Europea.",
    "Carnet de conducir": "Patente di guida", "No.": "No", "Movilidad": "Mobilità",
    "Disponibilidad inmediata. Presencial en Valencia o en remoto desde cualquier lugar.": "Disponibilità immediata. In presenza a Valencia o da remoto da qualsiasi luogo.",
    "Disponibilidad inmediata. Puedo mudarme dentro de España (incluidas las islas) y a Italia, Suiza, Noruega, Islandia y Países Bajos.": "Disponibilità immediata. Posso trasferirmi in Spagna (isole comprese) e in Italia, Svizzera, Norvegia, Islanda e Paesi Bassi.",
    "Presencial en Valencia, en remoto desde cualquier lugar, o con traslado dentro de España y a Italia, Suiza, Noruega, Islandia y Países Bajos.": "In presenza a Valencia, da remoto da qualsiasi luogo, o con trasferimento in Spagna e in Italia, Svizzera, Norvegia, Islanda e Paesi Bassi.",
    "Gracias por llegar hasta aquí.": "Grazie per aver letto fin qui.",
    "Durante mucho tiempo pensé que tenía que elegir entre el cálculo y el dibujo. Estudié ingeniería, y mientras tanto aprendí diseño por mi cuenta, proyecto a proyecto, desde 2018. Con los años entendí que no eran dos caminos: la ingeniería me enseñó responsabilidad y constancia, a medir antes de opinar y a documentar bien; el diseño, a mirar cómo se siente un lugar y a escuchar lo que alguien necesita antes de dibujarlo. Hoy trabajo con las dos cosas a la vez.":
        "Per molto tempo ho pensato di dover scegliere tra il calcolo e il disegno. Ho studiato ingegneria e, nel frattempo, ho imparato il design da sola, progetto dopo progetto, dal 2018. Con gli anni ho capito che non erano due strade: l'ingegneria mi ha insegnato responsabilità e costanza, a misurare prima di dare un'opinione e a documentare bene; il design, a guardare come ci si sente in un luogo e ad ascoltare ciò di cui qualcuno ha bisogno prima di disegnarlo. Oggi lavoro con entrambe le cose insieme.",
    "Los últimos años fueron de viaje y de trabajo. Trabajé de manera independiente y en estudios con equipos grandes dentro de mi profesión; también fui ayudante de cocina, hice camas en hoteles, lavé platos en restaurantes y serví eventos grandes en Italia y pequeños en Australia. Eso me enseñó lo que vale llegar a tiempo, hacer bien lo que toca y cuidar a la persona que tienes delante. También a trabajar codo a codo con gente de todas partes, a no perder la calma cuando el ritmo aprieta y, de paso, a cocinar mucho mejor.":
        "Gli ultimi anni sono stati di viaggio e di lavoro. Ho lavorato in modo indipendente e in studi con team numerosi nella mia professione; sono stata anche aiuto cucina, ho rifatto letti negli hotel, lavato piatti nei ristoranti e servito eventi grandi in Italia e piccoli in Australia. Questo mi ha insegnato quanto vale arrivare in orario, fare bene ciò che tocca e prendersi cura della persona che si ha davanti. E anche a lavorare fianco a fianco con persone di ogni parte del mondo, a non perdere la calma quando il ritmo si fa intenso e, per inciso, a cucinare molto meglio.",
    "Me gusta preguntar mucho antes de empezar y explicar el porqué de cada decisión.": "Mi piace fare molte domande prima di cominciare e spiegare il perché di ogni decisione.",
    "Viajo desde que terminé la carrera y la curiosidad no se me ha pasado: ya son casi veinte países, algunos apenas de paso. Por eso llevo a todas partes una cámara de segunda mano: para retratar lo que no quiero olvidar.":
        "Viaggio da quando ho finito l'università e la curiosità non mi è passata: sono già quasi venti paesi, alcuni solo di passaggio. Per questo porto ovunque una macchina fotografica di seconda mano: per ritrarre ciò che non voglio dimenticare.",
    "Si estás leyendo esto, seguramente buscas a alguien para tu estudio, tu restaurante, tu local o tu hotel. Me encantaría contarte más en persona. Escríbeme.":
        "Se stai leggendo queste righe, probabilmente cerchi qualcuno per il tuo studio, il tuo ristorante, il tuo negozio o il tuo hotel. Mi farebbe piacere raccontarti di più di persona. Scrivimi.",
    "Quién soy.": "Chi sono.", "Qué hago.": "Cosa faccio.", "Toda la trayectoria.": "Tutto il percorso.",
    "Desde 2007 hasta la actualidad.": "Dal 2007 a oggi.", "Lo práctico.": "Le cose pratiche.",
    "Herramientas e idiomas.": "Strumenti e lingue.", "Idiomas": "Lingue", "Fotografía.": "Fotografia.",
    "Mi afición. Me ayuda a desconectar y a mirar mejor.": "La mia passione. Mi aiuta a staccare e a guardare meglio.",
    "Hablemos.": "Parliamone.", "Un correo o un mensaje. Respondo en el día.": "Una mail o un messaggio. Rispondo in giornata.",
    "Descargar el CV en PDF": "Scarica il CV (PDF)",
    "Escríbeme": "Scrivimi", "Volver arriba": "Torna su", "Entrar": "Entra", "Menú": "Menu",
    "Ir al contenido": "Vai al contenuto", "Cambiar entre modo claro y oscuro": "Alterna modalità chiara e scura",
    "Modo claro / oscuro": "Modalità chiara / scura", "Áreas": "Aree", "fotos": "foto", "Idioma": "Lingua",
    "Valencia, España · 2026": "Valencia, Spagna · 2026",
    "Ingeniera civil · Técnica de proyectos · Diseñadora gráfica": "Ingegnera civile · Tecnica progettista · Graphic designer",
    "Ingeniera civil y diseñadora gráfica argentina, viviendo actualmente en Valencia, España. Elige el área que te interesa: verás primero lo que buscas y, debajo, toda la trayectoria.":
        "Ingegnera civile e graphic designer argentina, attualmente a Valencia, Spagna. Scegli l'area che ti interessa: vedrai prima ciò che cerchi e, sotto, tutto il percorso.",
    "Ingeniera civil, técnica de proyectos y diseñadora de marca en Valencia. Cómputos y presupuestos, diseño de marca, hostelería y ventas.":
        "Ingegnera civile, tecnica progettista e brand designer a Valencia. Computi e preventivi, brand design, ospitalità e vendita.",
    "Ingeniera civil · Diseñadora de marca": "Ingegnera civile · Brand designer",
    "Hola Natalia, vi tu portafolio y me gustaría hablar contigo.": "Ciao Natalia, ho visto il tuo portfolio e vorrei mettermi in contatto con te.",
    "Correo copiado": "Email copiata",
    "Copiar": "Copia", "Abrir en Gmail": "Apri in Gmail", "Abrir en Outlook": "Apri in Outlook",
    "Programa de correo": "App di posta", "Cerrar": "Chiudi", "Escribir a": "Scrivi a",
}

MESES = {
    "es": ["", "ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic"],
    "en": ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    "it": ["", "gen", "feb", "mar", "apr", "mag", "giu", "lug", "ago", "set", "ott", "nov", "dic"],
}

TR = {"es": {}, "en": EN, "it": IT}
